apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-apps
  namespace: cluster-config
spec:
  interval: 1m0s
  ref:
    branch: flux_overlay
  url: https://github.com/bavneetsingh16/arc-k8s-demo
  include:
    - repository:
        name: cluster-config
      fromPath: apps/staging
      toPath: cluster-apps/apps/staging
    - repository:
        name: cluster-config
      fromPath: apps/base/podinfo
      toPath: cluster-apps/apps/base/podinfo